version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"  # Assuming Nginx serves frontend on port 80
    working_dir: /app
    volumes:
      - ./client:/app
    restart: unless-stopped
